# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-07 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=255)),
                ('last_name', models.CharField(default='last name', max_length=255)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('date_of_birth', models.DateField(default='none')),
                ('bio', models.TextField(default='bio')),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
    ]
