# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191015_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank='True', upload_to='media/'),
        ),
    ]
