# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191015_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank='True', upload_to='images/'),
        ),
    ]
