# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191015_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='second_email',
            field=models.EmailField(default='Second_example@example.com', max_length=254),
        ),
    ]
